// <auto-generated />
namespace WypozyczalniaSamochodow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class usunieemaildaneklienta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usunieemaildaneklienta));
        
        string IMigrationMetadata.Id
        {
            get { return "201803171656066_usunie-email-daneklienta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
